stages:
    - install

variables:
    GIT_BRN: master
    KUBECTL_IMAGE: atlassian/pipelines-kubectl:latest

install_jobe:
    stage: install
    script:
        - docker build --tag AmLis_bot:v0.1 AnimeLists_bot/.
        - kubectl -aplly ./animelists/'Kubernetes manifest '/deploymet.yaml
