variables:
  IMAGE_TAG: sleepingfrand/anlis:$CI_COMMIT_REF_SLUG
  DOCKER_TLS_CERTDIR: "/certs"

build-push-docker-image-job:
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE_TAG ./AnimeLists_bot/
    - docker push $IMAGE_TAG
