apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.selector.matchLabels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.selector.matchLabels.app }}
    spec:
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: {{ .Values.deployment.container.image }}
          imagePullPolicy: {{ .Values.deployment.container.imagePullPolicy }}
          env:
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: telegram-secret
                key: token
          volumeMounts:
            - name: {{ .Values.deployment.volumes.name }}
              mountPath: {{ .Values.deployment.volumes.mountPath }}
      volumes:
        - name: {{ .Values.deployment.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
